name: Sync Fork

on:
  schedule:
    - cron: '0 */6 * * *' # At minute 0 past every 6th hour
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2.0
        with:
          base: master
          head: master